"""add puzzle and solve_attempt tables

Revision ID: a1de780ad291
Revises: 502f2c888447
Create Date: 2026-05-31 22:49:16.126828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a1de780ad291'
down_revision: Union[str, Sequence[str], None] = '502f2c888447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puzzle_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('puzzle_date', sa.Date(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('grid_data', sa.Text(), nullable=False),
    sa.Column('clues_data', sa.Text(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('puzzle_type', 'puzzle_date', name='uix_puzzle_type_date')
    )
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_puzzle_puzzle_date'), ['puzzle_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_puzzle_puzzle_type'), ['puzzle_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_puzzle_status'), ['status'], unique=False)

    op.create_table('solve_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('puzzle_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('seconds', sa.Integer(), nullable=True),
    sa.Column('grid_state', sa.Text(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'puzzle_id', name='uix_solve_user_puzzle')
    )
    with op.batch_alter_table('solve_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solve_attempt_puzzle_id'), ['puzzle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solve_attempt_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solve_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solve_attempt_user_id'))
        batch_op.drop_index(batch_op.f('ix_solve_attempt_puzzle_id'))

    op.drop_table('solve_attempt')
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_puzzle_status'))
        batch_op.drop_index(batch_op.f('ix_puzzle_puzzle_type'))
        batch_op.drop_index(batch_op.f('ix_puzzle_puzzle_date'))

    op.drop_table('puzzle')
    # ### end Alembic commands ###
